[book]
authors = ["Techidaily"]
language = "en"
multilingual = false
src = "src"
title = "XPotter"
description = "The site of the XPotter application."

[build]
build-dir = "../../products/xpotter"
create-missing = false